version: '3.9'

services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${DB_NAME:-filazero}
      MYSQL_USER: ${DB_USER:-filazero}
      MYSQL_PASSWORD: ${DB_PASS:-filazero}
    ports:
      - "3307:3306"
    volumes:
      - ./data/mysql/data:/var/lib/mysql
      - ./data/mysql/backup:/backup/mysql
    networks:
      - filazero_net

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis/data:/data
      - ./data/redis/backup:/backup/redis
    networks:
      - filazero_net

  backend:
    image: 171430923691.dkr.ecr.us-east-1.amazonaws.com/filazero-admin-backend:v1.2.0
    pull_policy: always
    restart: unless-stopped
    depends_on:
      - mysql
      - redis
    networks:
      - filazero_net
    env_file:
      - .env
    environment:
      NODE_ENV: production
      PORT: 80
      JWT_SECRET: ${JWT_SECRET:-supersecret}
      DB_NAME: ${DB_NAME:-filazero}
      DB_USER: ${DB_USER:-filazero}
      DB_PASS: ${DB_PASS:-filazero}
      DB_HOST: mysql
      DB_PORT: 3306
      TZ: ${TZ:-America/Sao_Paulo}
      REDIS_URL: redis://redis:6379
      FRONTEND_URL: ${FRONTEND_URL:-https://painel.filazerobrasil.com.br}
      ADMIN_PANEL_URL: ${ADMIN_PANEL_URL:-https://painel.filazerobrasil.com.br}
      PASSWORD_RESET_BASE_URL: ${PASSWORD_RESET_BASE_URL:-https://painel.filazerobrasil.com.br}
      RESET_PASSWORD_EXPIRES_MINUTES: ${RESET_PASSWORD_EXPIRES_MINUTES:-60}
      PUBLIC_API_URL: ${PUBLIC_API_URL:-https://api.filazerobrasil.com.br/api}
      ALLOW_SUPER_ADMIN_WITHOUT_DOMAIN: ${ALLOW_SUPER_ADMIN_WITHOUT_DOMAIN:-false}
      
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION:-us-east-1}

      S3_BUCKET_NAME: ${S3_BUCKET_NAME}

      RESEND_API_KEY: ${RESEND_API_KEY}
      RESEND_FROM: ${RESEND_FROM}
      EMAIL_LOGO_URL: ${EMAIL_LOGO_URL}
      FIREBASE_SERVICE_ACCOUNT_PATH: ${FIREBASE_SERVICE_ACCOUNT_PATH:-firebase-service-account.json.json}
      FIREBASE_SERVICE_ACCOUNT_JSON: ${FIREBASE_SERVICE_ACCOUNT_JSON}
    expose:
      - "4000"
    volumes:
      - ./data/backend/uploads:/app/public/uploads
      - ./data/backend/backup:/backup/uploads

  frontend:
    image: 171430923691.dkr.ecr.us-east-1.amazonaws.com/filazero-admin-frontend:v1.2.1
    pull_policy: always
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - filazero_net
    expose:
      - "80"

  caddy:
    image: caddy:2
    restart: unless-stopped
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./data/caddy/data:/data
      - ./data/caddy/config:/config
    networks:
      - filazero_net

networks:
  filazero_net:
    driver: bridge
